project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - "files/"
    - "projects/"
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/img/"
    - "slides/libs/"
    - "slides/css/"
    - "slides/*_files/"

# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl

website:
  title: "Estadística Descriptiva"
  site-url: "https://descriptiva-facso.netlify.app"
  #description: "Diseño, análisis, reporte y visualización de encuestas sociales"
  favicon: "/files/logo-removebg-preview.png"

  twitter-card:
    image: "/files/logo.png"
    card-style: summary_large_image
    creator: "@andreaslaffert"
    site: "@andreaslaffert"

  open-graph:
    image: "/files/logo.png"
    locale: en_US

  navbar:
    pinned: true
    background: "#069393"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Clases"
        file: class/index.qmd
      - text: "Prácticos"
        file: content/index.qmd
#      - text: "Assignments"
#        file: assignment/index.qmd
#      - text: "Examples"
#        file: example/index.qmd
      - trabajos.qmd
      - text: "Recursos"
        file: resource/index.qmd
      - text: "RStudio Cloud"
        href: "https://login.rstudio.cloud/login?redirect=%2F"

  sidebar:
    - title: "Clases"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Información general"
          contents:
            - class/index.qmd
        - section: "Sesiones"
          contents:
            - text: "1: Presentación al curso"
              file: class/01-class.qmd
            - text: "2: Caracterización de la investigación cuantitativa"
              file: class/02-class.qmd
            - text: "3: Medición y operacionalización"
              file: class/03-class.qmd
            - text: "4: Manejo de bases de datos"
              file: class/04-class.qmd
            - text: "5: Descripción de los datos"
              file: class/05-class.qmd
            - text: "6: Función y distribución de variables"
              file: class/06-class.qmd
            - text: "7: Introducción a la inferencia estadística"
              file: class/07-class.qmd



    - title: "Practicos"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Información general"
          contents:
            - content/index.qmd
        - section: "Sesiones"
          contents:
            - text: "1: Introducción al lenguaje R"
              file: content/01-content.qmd
            - text: "2: Conocimientos básicos de programación en R"
              file: content/02-content.qmd
            - text: "3: Procesamiento, limpieza y manipulación de datos en R"
              file: content/03-content.qmd
            - text: "4: Análisis descriptivo de datos en R"
              file: content/04-content.qmd
            - text: "5: Procesamiento y análisis de datos en R"
              file: content/05-content.qmd
            - text: "6: Visualización de datos con R"
              file: content/06-content.qmd
            - text: "7: Forma de una distribución"
              file: content/07-content.qmd
            - text: "8: Inferencia estadística univariada"
              file: content/08-content.qmd

    - title: "Recursos"
      style: "docked"
      search: false
      background: dark
      contents:
        - text: "Descripción"
          file: resource/index.qmd
        - text: "Bases de Datos"
          file: resource/01-resource.qmd
        - text: "Uso de R"
          file: resource/02-resource.qmd
        - text: "Importar datos en R"
          file: resource/03-resource.qmd
        - text: "Procesamiento, limpieza y manipulación de datos en R base"
          file: resource/04-resource.qmd





  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
